### ISSUE TITLE
create release/tag repo when we make an npm release

### ISSUE THREAD

**Issue by rabbah** [nimbella/nimbella-cli-plugins#8]

**Comment by bhageena** [comment]
Releases made hitherto have been tagged manually. Going forward we will use `build.sh` in root dir. 
`./build.sh -p postman -v patch -d`
here 
`-p` is the plugin name i.e. [postman, openapi, apispecgen]
`-v` is the version to be updated i.e. [major, minor, patch, 1.2.0, ...]
`-d` is for deploy, if you are logged into npm, it'll publish the plugin to the npm registry.
