### ISSUE TITLE
Explain in README how to get the postman API key

### ISSUE THREAD

**Issue by niks3089** [nimbella/nimbella-cli-plugins#9]
I have been asked this question couple of times. We should also explain what is the postman API key, the scope of the key and what can be done with it

**Comment by rabbah** [comment]
Take some of the docs from https://github.com/rabbah/nimbella-postman

**Comment by bhageena** [comment]
> I have been asked this question couple of times. We should also explain what is the postman API key, the scope of the key and what can be done with it

Currently, a link `Postman Integrations Dashboard` is given in the postman doc under [Create Project](https://github.com/nimbella/nimbella-cli-plugins/blob/main/postman/README.md#create-project) header.

I'll make a separate section explaining that.
